-- DROP DATABASE
DROP DATABASE IF EXISTS volunteer_db;

-- CREATE DATABASE
CREATE DATABASE volunteer_db;

-- DROP DATABASE
DROP DATABASE IF EXISTS recipe_db;

-- CREATE DATABASE
CREATE DATABASE recipe_db;
