import { Recipe } from '../models/index.js';

export const seedRecipes = async () => {
  await Recipe.bulkCreate([
    {
      title: "Rosemary and Red Onion Focaccia", 
      summary: "Rosemary and Red Onion Focaccia is a bread that serves 16. One portion of this dish contains approximately <b>3g of protein</b>, <b>3g of fat</b>, and a total of <b>141 calories</b>. For <b>16 cents per serving</b>, this recipe <b>covers 5%</b> of your daily requirements of vitamins and minerals. It is a <b>very reasonably priced</b> recipe for fans of Mediterranean food. 1 person were impressed by this recipe. It is brought to you by Foodista. If you have lemon zest, rosemary, olive oil, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>dairy free and lacto ovo vegetarian</b> diet. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 49%</b>, this dish is good. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/rosemary-and-red-onion-focaccia-80012\">Rosemary And Red Onion Focaccia</a>, <a href=\"https://spoonacular.com/recipes/rosemary-and-red-onion-focaccia-551751\">Rosemary and Red Onion Focaccia</a>, and <a href=\"https://spoonacular.com/recipes/rosemary-and-red-onion-focaccia-506954\">Rosemary and Red Onion Focaccia</a>.", 
      readyInMinutes: 45, 
      servings: 16, 
      //ingredients: ["3 tablespoons olive oil+ extra for bowl and pans",  "1 cup cold water", "1/4 cup lukewarm water", "1 teaspoon salt", "2 tablespoons fresh chopped rosemary", "3 tablespoons chopped red onion (or shallot)+ extra slices for top", "4 cups all-purpose flour", "Salt and Pepper","1 package of dry active yeast","1 teaspoon honey","1 Zest of lemon",], 
      instructions: "Pour the warm water and honey into the bowl of your electric mixer with a paddle attachment. Add one package of dry active yeast and swirl around. Allow the yeast to foam for 10 minutes or so. Then add the cold water, lemon zest, 2 Tb. oil, salt, rosemary and onions. Turn the mixer on low and slowly add the flour. Once all the flour is in the bowl, switch the paddle to the bread hook attachment. Knead on low for about 10 minutes.\nPull the dough away from the sides and rub the bowl down with oil. Cover the bowl with plastic wrap and allow the dough to rise for 1  to 2 hours. Remove the plastic wrap and turn the mixer back on for 30 seconds.\nDivide the dough into two pieces and press with your fingers into two 9-10 inch round pans. As you press to dough to the edges, dont be afraid to let your fingers puncture the doughthis will created the bumpy, rustic texture of traditional focaccia.\nCover both pans with a clean, damp towel. Allow the dough to rise again for another 2 hours. Preheat the oven to 400* F. Before baking use the remaining tablespoon of oil and brush the tops of the loaves. Sprinkle with salt and pepper and decorate with thin onion slices, if you like.\nBake for 25-30 minutes, until the tops are golden-brown. Turn out the bread loaves and ENJOY!", 
      //steps: ["Pour the warm water and honey into the bowl of your electric mixer with a paddle attachment.", "Add one package of dry active yeast and swirl around. Allow the yeast to foam for 10 minutes or so. Then add the cold water, lemon zest, 2 Tb. oil, salt, rosemary and onions. Turn the mixer on low and slowly add the flour. Once all the flour is in the bowl, switch the paddle to the bread hook attachment. Knead on low for about 10 minutes.", "Pull the dough away from the sides and rub the bowl down with oil. Cover the bowl with plastic wrap and allow the dough to rise for 1  to 2 hours.", "Divide the dough into two pieces and press with your fingers into two 9-10 inch round pans. As you press to dough to the edges, dont be afraid to let your fingers puncture the doughthis will created the bumpy, rustic texture of traditional focaccia.", "Cover both pans with a clean, damp towel. Allow the dough to rise again for another 2 hours. Preheat the oven to 400* F. Before baking use the remaining tablespoon of oil and brush the tops of the loaves.", "Sprinkle with salt and pepper and decorate with thin onion slices, if you like.", "Bake for 25-30 minutes, until the tops are golden-brown. Turn out the bread loaves and ENJOY!"], 
      image: "https://img.spoonacular.com/recipes/658782-556x370.jpg", 
      sourceUrl: "https://www.foodista.com/recipe/8PZLGG3C/rosemary-and-red-onion-focaccia",
      spoonacularSourceUrl: "https://spoonacular.com/rosemary-and-red-onion-focaccia-658782",
      spoonacularId: 658782
    }
  ]);
};

